### ISSUE TITLE
Juju status blocked

### ISSUE THREAD

**Issue by aym-frikha** [canonical/maas-anvil#12]
Hello,

After letting the maas cluster running for a day, i tried to do juju status on one node, but got message that I need to enter password for the host on anvill-controller.

![image](https://github.com/canonical/maas-anvil/assets/1623989/651332b0-512f-401d-b4f6-4997fde76ddc)

**Comment by marosg42** [comment]
@aym-frikha I think you included wrong screenshot. Anyhow, password is located in `~/snap/maas-anvil/current/account.yaml`

**Comment by aym-frikha** [comment]
Is it possible please to explain to me the benefit of this process where having the random password located in ~/snap/maas-anvil/current/account.yaml ? From user experience perspective I don't think it's ideal. specially if it's not documented

**Comment by skatsaounis** [comment]
Hi @aym-frikha , With #34 we added the `juju-login` command that sunbeam is also using to manage this situation. We also added documentation notes on why and when this command is needed. Feel free to try the command during one of your next Anvil deployments. Thank you for detecting the issue in the first place :beer:
