### ISSUE TITLE
[feature-request] Enable TLS in MAAS

### ISSUE THREAD

**Issue by baycarbone** [canonical/maas-anvil#44]
(I'm not sure if this feature request should be related to maas-anvil or to the maas charms, so feel free to reject if this is not the right place.)

It would be nice if we could enable TLS (https://maas.io/docs/how-to-implement-tls) through automation.

**Comment by skatsaounis** [comment]
Hi @baycarbone .

Thank you for opening this one. You are right as this feature expands to maas-region charm as well. It seems that we need to enable it at charm level before adding it to Anvil. Could you please open a similar issue there and link it with this one?
